### ISSUE TITLE
Ditto++ - Main Application Window is Blank ... Mac OS 10.13.6

### ISSUE THREAD

**Issue by SeaMac** [RubinderS/DittoPlusPlus#10]
Ditto++ - Main Application Window is Blank when Launched on Mac OS 10.13.6 

I downloaded the latest version. I moved it to my Utilities Folder. I launched it - and gave it permission to run. Icon shows in the System Menu Bar. Icon only has "Hide/Show" and "Quit" choices drop down. Main window is BLANK. Hiding and restoring it didn't help. I quit the App. Those two menubar Icon Functions work OK but everything else is just a Blank.

![image](https://user-images.githubusercontent.com/5051781/139615902-5f9c9867-eb8e-4c80-b8a0-b5df3ba7577d.png)

![image](https://user-images.githubusercontent.com/5051781/139616016-4103d31b-672d-451e-8fe3-4dd3bf8a9cc6.png)

**Comment by PabloLION** [comment]
same for me.. I thought it was M1 compatibility problem

**Comment by RubinderS** [comment]
Hi thanks for raising this
Its shouldn't be an M1 issue as I'm also using it on M1

Is the possible if you could build and run the app (using instructions in the Readme.me) and post the results here

Thanks

**Comment by PabloLION** [comment]
Hi @RubinderS, I've tried re-install the app and following the "How to use" in the README.md. The problem remains the same. I searched for `Readme.me` in case that it's another file than `Readme.md` but there's no such file in this repo. Could you post some link to this file? Thanks.

**Comment by RubinderS** [comment]
Sorry, I thought I had added build instructions in the Readme file
Anyways, use the following steps to re-build it on your system

> make sure you have removed/uninstalled Ditto++ from your system

 Clone the repository on your machine and run the following commands

- `npm i` 
- `npm run pkg:mac`

This will create a binary file in `./out/Ditto++***.dmg` 
use this file to install Ditto++

**Comment by PabloLION** [comment]
Hi RubinderS,
Thank you for your reply.  
My `npm run pkg:mac` gives

```
> dittoplusplus@1.0.3 pkg:mac
> npm run pkg && electron-builder build --mac --x64


> dittoplusplus@1.0.3 pkg
> rimraf out && cross-env IS_Packaged=true NODE_ENV=production npm run build


> dittoplusplus@1.0.3 build
> eslint ./src/**/*.ts && rimraf dist && webpack --progress --color


Oops! Something went wrong! :(

ESLint: 7.14.0

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Failed to load plugin 'react' declared in '.eslintrc.js': Package subpath './2020/AddEntriesFromIterable' is not defined by "exports" in /Users/pablo/LocalDocs/project/dpp/DittoPlusPlus/node_modules/es-abstract/package.json
Referenced from: /Users/pablo/LocalDocs/project/dpp/DittoPlusPlus/.eslintrc.js
    at new NodeError (node:internal/errors:371:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:429:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:683:3)
    at resolveExports (node:internal/modules/cjs/loader:482:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (/Users/pablo/LocalDocs/project/dpp/DittoPlusPlus/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/Users/pablo/LocalDocs/project/dpp/DittoPlusPlus/node_modules/object.fromentries/implementation.js:3:30)
```
And the `./out/Ditto++***.dmg` was not created.

Could you have a look at my problem?

**Comment by PabloLION** [comment]
I was running with nodejs 17

**Comment by RubinderS** [comment]
Try deleting `package-lock.json` file and repeat the steps above

**Comment by RubinderS** [comment]
or in the first step instead of `npm i` run `npm i --legacy-peer-deps`

**Comment by PabloLION** [comment]
Hi again @RubinderS . I removed `package-lock.json` and `node_modules` then I did `npm i --legacy-peer-deps` and `npm run pkg:mac` and got this.

```
> dittoplusplus@1.0.3 pkg:mac
> npm run pkg && electron-builder build --mac --x64


> dittoplusplus@1.0.3 pkg
> rimraf out && cross-env IS_Packaged=true NODE_ENV=production npm run build


> dittoplusplus@1.0.3 build
> eslint ./src/**/*.ts && rimraf dist && webpack --progress --color

10% building 0/1 entries 0/0 dependencies 0/0 modulesError: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at BulkUpdateDecorator.hashFactory ($LocalDocs/project/dpp/DittoPlusPlus/node_modules/webpack/lib/util/createHash.js:145:18)
    at BulkUpdateDecorator.update ($LocalDocs/project/dpp/DittoPlusPlus/node_modules/webpack/lib/util/createHash.js:46:50)
    at RawSource.updateHash ($LocalDocs/project/dpp/DittoPlusPlus/node_modules/webpack-sources/lib/RawSource.js:77:8)
    at NormalModule._initBuildHash ($LocalDocs/project/dpp/DittoPlusPlus/node_modules/webpack/lib/NormalModule.js:870:17)
    at handleParseResult ($LocalDocs/project/dpp/DittoPlusPlus/node_modules/webpack/lib/NormalModule.js:936:10)
    at $LocalDocs/project/dpp/DittoPlusPlus/node_modules/webpack/lib/NormalModule.js:1028:4
    at processResult ($LocalDocs/project/dpp/DittoPlusPlus/node_modules/webpack/lib/NormalModule.js:745:11)
    at $LocalDocs/project/dpp/DittoPlusPlus/node_modules/webpack/lib/NormalModule.js:809:5
10% building 0/1 entries 1/1 dependencies 0/1 modules$LocalDocs/project/dpp/DittoPlusPlus/node_modules/loader-runner/lib/LoaderRunner.js:146
		if(isError) throw e;
		            ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at BulkUpdateDecorator.hashFactory ($LocalDocs/project/dpp/DittoPlusPlus/node_modules/webpack/lib/util/createHash.js:145:18)
    at BulkUpdateDecorator.update ($LocalDocs/project/dpp/DittoPlusPlus/node_modules/webpack/lib/util/createHash.js:46:50)
    at RawSource.updateHash ($LocalDocs/project/dpp/DittoPlusPlus/node_modules/webpack-sources/lib/RawSource.js:77:8)
    at NormalModule._initBuildHash ($LocalDocs/project/dpp/DittoPlusPlus/node_modules/webpack/lib/NormalModule.js:870:17)
    at handleParseResult ($LocalDocs/project/dpp/DittoPlusPlus/node_modules/webpack/lib/NormalModule.js:936:10)
    at $LocalDocs/project/dpp/DittoPlusPlus/node_modules/webpack/lib/NormalModule.js:1028:4
    at processResult ($LocalDocs/project/dpp/DittoPlusPlus/node_modules/webpack/lib/NormalModule.js:745:11)
    at $LocalDocs/project/dpp/DittoPlusPlus/node_modules/webpack/lib/NormalModule.js:809:5 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v17.1.0
```

**Comment by PabloLION** [comment]
I'm trying to write me program with Electron but I just started.

**Comment by PabloLION** [comment]
Any update here?
